#!/bin/bash

function compareConfDir {
    rep1="${1}"
    rep2="${2}"
    for f1 in api/"${rep1}"/*
    do
        f2="api/${rep2}/$(basename $f1)"
        if ! [ -f "$f1" ]
        then
            echo "$f1 does not exist at contrary to $f2" >&2
            exit 1
        fi
        SED_CMD='sed -e "s/.*\(PREVIOUS\|CURRENT\|NEXT\)_YEAR.*//" -e "s/.*DOC_ID.*SHEET_ID.*//" ' \
            ' -e "s/\(define(.*, \).*\();\)/\1\2/" -e "s/array(.*)/array()/" -e "s/^#//" ' \
            ' -e "s/^.*# git-hook-ignore//"'
        if ! diff -B -q <(eval $SED_CMD "$f1") <(eval $SED_CMD "$f2")
        then
            echo "$f1 differs from $f2 :" >&2
            diff <(eval $SED_CMD "$f1") <(eval $SED_CMD "$f2") >&2
            exit 1
        fi
    done
    for f2 in api/"${rep2}"/*
    do
        f1="api/${rep1}/$(basename $f1)"
        if ! [ -f "$f2" ]
        then
            echo "$f2 does not exist at contrary to $f1" >&2
            exit 1
        fi
    done
}

compareConfDir "conf_template" "conf_prod"
compareConfDir "conf_template" "conf_it"

if ! diff -q api/sqlscripts/create.sql <(eval sed -e "s/it_/vcr_/" api/tests/sqlscripts/it_create.sql) 1>/dev/null
then
    echo "api/sqlscripts/create.sql differs from api/tests/sqlscripts/it_create.sql"
    diff api/sqlscripts/create.sql <(eval sed -e "s/it_/vcr_/" api/tests/sqlscripts/it_create.sql)
    exit 1
fi

exit 0

